FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements-bot.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY bleach_bot/bot/pika_client.py pika_client.py
COPY bleach_bot/bot/bot.py bot.py


CMD [ "python3", "bot.py"]