
FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements-predictor.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY data/toxicity_model.onnx toxicity_model.onnx
COPY data/tokenizer.json tokenizer.json
COPY bleach_bot/predictor/predictor.py predictor.py



CMD [ "python3", "predictor.py"]